namespace: flux-system
resources:
- namespace.yaml
bases:
- github.com/fluxcd/helm-operator//deploy
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-operator
    namespace: flux-system
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - --enabled-helm-versions=v3
secretGenerator:
- name: helm-repositories
  files:
    - repositories.yaml
patchesStrategicMerge:
- patch-git-secret.yaml
